### ISSUE TITLE
Add gradient borders for articles in `Blog.html`

### ISSUE THREAD

**Issue by dylanOshima** [dylanOshima/dylanOshima.github.io#7]
An implementation works with:
```css
.article-border { 
  background: linear-gradient(var(--page-bg-color), var(--page-bg-color)), 
            linear-gradient(to right, blue, red, green);
  background-origin: padding-box, border-box;
  background-repeat: no-repeat; /* this is important */
  border: 10px solid transparent;
  border-radius: 20px;
  position: relative;
  /* Animations */
  transition: transform 0.5s ease, box-shadow 0.5s ease;
}

.article-border::before {
  content: "";
  position: absolute;
  top: -6px;
  bottom: -6px;
  left: -6px;
  right: -6px;
  border: 6px solid var(--page-bg-color);
  border-radius: 20px;
}
```
which is taken from [this codepen](https://codepen.io/AlexOverbeck/pen/axGQyv?editors=1100)
but it has some bugs with the transitions.
